### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Rxn-bit** [AdrMXR/KitHack#26]

**Comment by AdrMXR** [comment]
?

**Comment by indianprogrammer01** [comment]
hey,Adr what is this code all about

**Comment by AdrMXR** [comment]
> hey,Adr what is this code all about
You have the documentation in this [section](https://github.com/AdrMXR/KitHack/blob/master/docs/translations/English/README.md)

**Comment by AdrMXR** [comment]
You have the documentation in this [section](https://github.com/AdrMXR/KitHack/blob/master/docs/translations/English/README.md)

**Comment by mandeepk3335** [comment]
How to use it,this is python code ibdont know how to use this.tell me

**Comment by AdrMXR** [comment]
Read the [installation instructions](https://github.com/AdrMXR/KitHack/blob/master/docs/translations/English/README.md#installation)



> How to use it,this is python code ibdont know how to use this.tell me
