### ISSUE TITLE
KitHack no actualiza el NGROK

### ISSUE THREAD

**Issue by isa84sfs** [AdrMXR/KitHack#3]
He seguido los pasos que se muestran en el video de YouTube, pero el ngrok siempre se muestra como ninguno. Authtoken se actualiza correctamente en el archivo ngrok.yml e incluso el archivo ngrok.tcp se actualiza pero ngrok todavía no muestra ninguno

I have followed the steps as shown in youtube video but the ngrok always shows as none. Authtoken is update in ngrok.yml file correctly and even the ngrok.tcp file is updated but ngrok still shows none

**Comment by AdrMXR** [comment]
¿Tiene actualizado kithack? Hace unos días he incorporado la solución a ese problema, por favor ejecute el archivo "update.sh" en su directorio KitHack con permisos de sudo para actualizar.
En caso de que siga generando problemas, por favor incorpore una fotografía o mandeme los detalles al correo kithacking@gmail.com

**Comment by AdrMXR** [comment]
Debido a la tardanza de respuesta cerraré este caso, recalco que la solución ha sido implementada en la ultima versión de kithack y cualquier problema mandar los detalles al correo kithacking@gmail.com
