### ISSUE TITLE
Docker KitHack Container

### ISSUE THREAD

**Issue by tory1103** [AdrMXR/KitHack#40]
Hola Adrian.
Abro este hilo para informarte que he creado un contenedor de docker de kithack.
El contenedor usa kali-linux como OS, instalara kithack automaticamente una vez iniciado.
Aqui te dejo un link al contenedor, si quieres mas creditos o no quieres que lo publique, avisame...
Link: https://hub.docker.com/repository/docker/adriantoral/kithack

**Comment by AdrMXR** [comment]
Ok, genial 👍
