### ISSUE TITLE
Error al iniciar

### ISSUE THREAD

**Issue by Andonicio83** [AdrMXR/KitHack#51]
### Información
1. **Version de KitHack utilizada: `v1.3.2`** 
2. **Distribución Linux utilizada: `Kali linux`**
3. **Asunto del problema: `problema de ejecución`**

### Stack trace
```
─$ kithack
Traceback (most recent call last):
  File "/home/USER/KitHack/KitHack.py", line 19, in <module>
    from lib.banners import *
ModuleNotFoundError: No module named 'lib.banners'
                                                    
```
A ver si me puedes ayudar
Gracias por tu tiempo

**Comment by AdrMXR** [comment]
Este problema es duplicado, lo puedes verificar [aquí](https://github.com/AdrMXR/KitHack/issues/27)
Sin embargo, aún no es digno de cerrar ya que el usuario no dio respuesta, te preguntaré lo mismo ¿Tienes una versión de KitHack alterada? Sino es así trata de reinstalar, o de ejecutar kithack desde el directorio y no desde el atajo

**Comment by Andonicio83** [comment]
Hola de nuevo, la version no esta alterada, es la clonada desde tu github. He probado a desinstalarla y volverla a instalar, a ejecutarla desde el directorio y nada me sale el mismo mensaje todo el rato. Es posible que entre en conflicto con alguna otra herramienta instalada?

**Comment by AdrMXR** [comment]
No lo creo, es un problema de las importaciones no te esta detectando los archivos python que se encuentran en la carpeta `lib`.
Intenta ejecutar este comando: `export PYTHONPATH="${PYTHONPATH}:/home/USER/KitHack/"`
Para agregar el directorio raíz de kithack a tu respectivo **pythonpath**

**Comment by AdrMXR** [comment]
Posterior a ello trata de volver a ejecutar kithack y me comentas si se soluciona.

**Comment by AdrMXR** [comment]
En el comando que te mencioné estoy considerando que el directorio de kithack en tu equipo es `/home/USER/KitHack/`
Si el directorio lo has cambiado remplázalo en el comando

**Comment by Andonicio83** [comment]
Nada, me sigue saliendo lo mismo. He reinstalado de nuevo el Kali pero me sigue saliendo el mismo error.
Gracias por tu ayuda

**Comment by AdrMXR** [comment]
¿Me puedes comentar tu versión de python instalada?

**Comment by Andonicio83** [comment]
Hola, perdona la tardanza en contestar, he estado unos dias desconectado
La version de Python:
Python 3.10.5
Gracias, un saludo

**Comment by AdrMXR** [comment]
Hola has intentando en reinstalar python?

**Comment by AdrMXR** [comment]
Ejecuta esto
`pip3 install requests`

**Comment by andonicio** [comment]
Ya lo he conseguido, he reinstalado kali con una instalacion basica sin complementos y siguinedo los pasos que indicas me ha funcionado sin ningun problema. Ahora toca probrar.
Muchas gracias por tu ayuda
